### ISSUE TITLE
Possibility for two processes to hold the lock

### ISSUE THREAD

**Issue by jdonszelmann** [LunaTheFoxgirl/m1racle-mutex#1]
On this line, it is possible that the two processes (1 and 2) are in the while loop waiting for the lock to unlock.

https://github.com/LunaTheFoxgirl/m1racle-mutex/blob/90e096b8abd9c93d64a1254016b32ece8dbef589/source/mutex.d#L22

If thread 1 reads the lock and sees it unlocked, it continues past the while loop. There are now several instructions being executed (such as the conditional jump to the start of the while loop which is not taken, and a call instruction possibly setting up a stackframe). If while thread 1 is executing these instructions thread 1 is scheduled out, it's possible for thread 2 to also observe the mutex as unlocked and also start running these instructions leading up to locking the mutex. Both threads may now lock it.

Though I know this project is mostly a joke, I thought I'd mention it. This isn't much better than just using a global variable except that with this vulnerability this mutex works between processes I guess :stuck_out_tongue:. Very cool idea for sure!

**Comment by LunaTheFoxgirl** [comment]
I did consider storing a thread id in to the register but since i can only write 2 bits to it it'd be useless. So it's more a limitation of the vulnerability than anything. Not to mention there is no way to do atomic reads/writes to the register in question that I know of.

**Comment by jdonszelmann** [comment]
haha no, I don't think that's possible. Very cool idea nonetheless. Just thought I'd mention it. To make it work properly you'd need some sort of compare and swap which is impossible as far as I know.

**Comment by LunaTheFoxgirl** [comment]
I'll close this with a link to my reasoning for creating this monstrosity.
https://twitter.com/LunaFoxgirlVT/status/1397431079057993728?s=20
